# CONFIGURAÇÕES DO H2
spring.datasource.url=jdbc:h2:mem:medconnect
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# O H2 recria as tabelas a cada reinicialização
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true